<?php defined('BASEPATH') OR exit('No direct script access allowed') ; ?>
#Nama, Obj, Lokasi, Icon, Lebar, Tinggi, title, resize, modal, frame, help, bodyclass, headerclass
#["Dashboard Center", "d", "admin/dash/d", "ion-ios-speedometer", 0, 0, false]
["Master", "mst", "", "ion-ios-briefcase"]
    ["Bank / Kas", "mstbankkas", "admin/mst/mstbankkas", "" ,800, 500, false]
    ["Uang Pecahan", "mstuangpecahan", "admin/mst/mstuangpecahan", "" ,800, 500, false]
    ["Kode Transaksi", "mstkdtransaksi", "admin/mst/mstkdtransaksi", "" ,800, 500, false]
    ["Rekening", "mstrekening", "admin/mst/mstrekening", "" ,800, 500, false]
    ["Aktiva, BDD dan Inventaris", "mstaktivainventaris", "admin/mst/mstaktivainventaris", "" ,800, 500, false]
    ["Gol. Aktiva, BDD dan Inventaris", "mstgolaktivainventaris", "admin/mst/mstgolaktivainventaris", "" ,800, 500, false]
    ["Gol. Stock", "mstgroupstock", "admin/mst/mstgroupstock", "" ,800, 500, false]
    ["Stock / Barang", "mstdatastock", "admin/mst/mstdatastock", "" ,800, 500, false]
    ["Satuan", "mstsatuan", "admin/mst/mstsatuan", "" ,800, 500, false]
    ["Gudang", "mstgudang", "admin/mst/mstgudang", "" ,800, 500, false]
    ["Supplier", "mstsupplier", "admin/mst/mstsupplier", "" ,800, 500, false]
["Transaksi", "tr", "", "ion-ios-briefcase"]
    ["Transaksi Purchase Request", "trpr", "admin/tr/trpr", "ion-cash", 850, 500,false]
    ["Transaksi Purchase Order", "trpo", "admin/tr/trpo", "ion-cash", 1050, 500,false]
    ["Transaksi Pembelian", "trpembelian", "admin/tr/trpembelian", "ion-cash", 900, 500,false]
    ["Transaksi Retur Pembelian", "trreturpembelian", "admin/tr/trreturpembelian", "ion-cash", 850, 500,false]
    ["Transaksi Pelunasan Hutang", "trpelunasanhutang", "admin/tr/trpelunasanhutang", "ion-cash", 850, 600,false]
    ["Cetak Price Card Gondola", "trcetakpricecard", "admin/tr/trcetakpricecard", "ion-cash", 900, 600,false]
    ["Cetak Barcode", "trcetakbarcode", "admin/tr/trcetakbarcode", "ion-cash", 500, 300,false]
    #["Transaksi Delivery Order", "trdo", "admin/tr/trdo", "ion-cash", 850, 500,false]
    #["Transaksi Surat Jalan", "trsj", "admin/tr/trsj", "ion-cash", 850, 500,false]
    #["Transaksi Penjualan", "trpenjualan","admin/tr/trpenjualan","ion-cash", 850, 550,false]
    #["Transaksi Retur Penjualan", "trreturpenjualan", "admin/tr/trreturpenjualan", "ion-cash", 850, 500,false]
    ["Transaksi Penjualan Kasir", "trpenjualankasir", "admin/tr/trpenjualankasir", "ion-cash", 1050, 600,false]
    #["Transaksi Pelunasan Piutang", "trpelunasanpiutang", "admin/tr/trpelunasanpiutang", "ion-cash", 850, 600,false]
    ["Transaksi Edit Penjualan", "treditpenjualan","admin/tr/treditpenjualan","ion-cash", 850, 600,false]
    ["Transaksi Cetak, Delete Penjualan", "trcetakstrukpenjualan","admin/tr/trcetakstrukpenjualan","ion-cash", 850, 500,false]
    ["Transaksi Mutasi Stock", "trmutasistock", "admin/tr/trmutasistock", "ion-cash", 900, 500,false]
    ["Transaksi Stock Opname", "trso", "admin/tr/trso", "ion-cash", 850, 500,false]
    ["Posting Stock Opname", "trsoposting", "admin/tr/trsoposting", "ion-cash", 850, 500,false]
    #["Transaksi Kas Masuk dan Keluar", "trkas", "admin/tr/trkas", "ion-cash", 1050, 500,false]
    ["Transaksi Mutasi Kas", "trmutasikas", "admin/tr/trmutasikas", "ion-cash", 1050, 500,false]
    ["Transaksi Opname Kas", "tropnamekas", "admin/tr/tropnamekas", "ion-cash", 1050, 500,false]
    #["Transaksi Mutasi Bank", "trmutasibank", "admin/tr/trmutasibank", "ion-cash", 1050, 500,false]
    #["Transaksi Mutasi BG", "trmutasibg", "admin/tr/trmutasibg", "ion-cash", 1050, 500,false]
    #["Transaksi Mutasi Persekot", "trmutasipersekot", "admin/tr/trmutasipersekot", "ion-cash", 1050, 500,false]
    #["Transaksi Mutasi Uang Muka", "trmutasiuangmuka", "admin/tr/trmutasiuangmuka", "ion-cash", 1050, 500,false]
    #["Transaksi Jurnal Umum", "trjurnal", "admin/tr/trjurnal", "ion-cash", 850, 600]
	["Transaksi Jurnal Umum", "trjurnallainlain", "admin/tr/trjurnallainlain", "ion-cash", 900, 600,false]
["Laporan", "rpt", "", "ion-ios-paper"]
    ["Lap. SPP", "rptpr","admin/rpt/rptpr", "ion-filing", 1200,600,false]
    ["Lap. Purchase Order", "rptpo","admin/rpt/rptpo", "ion-filing", 1200,600,false]
    ["Lap. Pembelian", "rptpembelianstock","admin/rpt/rptpembelianstock", "ion-filing", 1200,600,false]
    ["Lap. Retur Pembelian", "rptreturstock","admin/rpt/rptreturstock", "ion-filing", 1200,600,false]
    ["Lap. Pelunasan Hutang", "rptpelunasanhutang","admin/rpt/rptpelunasanhutang", "ion-filing", 800,600,false]
    ["Lap. Kartu Hutang", "rptkartuhutang","admin/rpt/rptkartuhutang", "ion-filing", 800,600,false]
    ["Lap. Saldo Hutang", "rptsaldohutang","admin/rpt/rptsaldohutang", "ion-filing", 800,600,false]
    #["Lap. Kartu Persekot", "rptkartupersekot","admin/rpt/rptkartupersekot", "ion-filing", 800,600,false]
    #["Lap. Saldo Persekot", "rptsaldopersekot","admin/rpt/rptsaldopersekot", "ion-filing", 800,600,false]
    #["Lap. Perintah Produksi", "rptperintahproduksi","admin/rpt/rptperintahproduksi", "ion-filing", 1200,600,false]
    #["Lap. Hasil Produksi", "rpthasilproduksi","admin/rpt/rpthasilproduksi", "ion-filing", 1200,600,false]
    #["Lap. Delivery Order", "rptdo","admin/rpt/rptdo", "ion-filing", 1200,600,false]
    #["Lap. Surat Jalan", "rptsj","admin/rpt/rptsj", "ion-filing", 1200,600,false]
    ["Lap. Penjualan", "rptpenjualan","admin/rpt/rptpenjualan", "ion-filing", 1200,600,false]
    #["Lap. Retur Penjualan", "rptreturpenjualan","admin/rpt/rptreturpenjualan", "ion-filing", 1200,600,false]
    #["Lap. Pelunasan Piutang", "rptpelunasanpiutang","admin/rpt/rptpelunasanpiutang", "ion-filing", 800,600,false]
    #["Lap. Kartu Piutang", "rptkartupiutang","admin/rpt/rptkartupiutang", "ion-filing", 800,600,false]
    #["Lap. Saldo Piutang", "rptsaldopiutang","admin/rpt/rptsaldopiutang", "ion-filing", 800,600,false]
    #["Lap. Kartu Uang Muka", "rptkartuuangmuka","admin/rpt/rptkartuuangmuka", "ion-filing", 800,600,false]
    #["Lap. Saldo Uang Muka", "rptsaldouangmuka","admin/rpt/rptsaldouangmuka", "ion-filing", 800,600,false]
    ["Lap. Daftar Aset & Penyusutan", "rptpenyusutanasetinv", "admin/rpt/rptpenyusutanasetinv", "ion-filing", 1200,600]
    ["Lap. Kartu Stock", "rptkartustock","admin/rpt/rptkartustock", "ion-filing", 800,600,false]
    ["Lap. Saldo Stock", "rptsaldostock","admin/rpt/rptsaldostock", "ion-filing", 800,600,false]
    ["Lap. Index Penjualan Stock", "rptindexpenjualanstock","admin/rpt/rptindexpenjualanstock", "ion-filing", 800,600,false]
    ["Lap. Buku Besar", "rptbukubesar", "admin/rpt/rptbukubesar", "ion-filing", 900,600]
    ["Lap. Jurnal", "rptjurnal", "admin/rpt/rptjurnal", "ion-filing", 800,600] 
	#["Lap. Neraca", "rptneraca", "admin/rpt/rptneraca", "ion-filing", 800,600]
    ["Lap. Neraca 2", "rptneraca2", "admin/rpt/rptneraca2", "ion-filing", 1200,600]
	["Lap. Laba Rugi", "rptlr", "admin/rpt/rptlr", "ion-filing", 800,600]
    #["Lap. Harga Pokok Produksi", "rpthpproduksi", "admin/rpt/rpthpproduksi", "ion-filing", 800,600,false]
	#["Lap. Harga Pokok Produksi Stock", "rpthpproduksistock", "admin/rpt/rpthpproduksistock", "ion-filing", 800,600]
    #["Lap. Harga Pokok Penjualan", "rpthppenjualan", "admin/rpt/rpthppenjualan", "ion-filing", 800,600,false]
    #["Lap. Analisa Ratio Keuangan", "rptanalisaratiokeu", "admin/rpt/rptanalisaratiokeu", "ion-filing", 800,600,false]
    #["Lap. Triwulan", "rpttriwulan", "admin/rpt/rpttriwulan", "ion-filing", 800,600,false]
	#["Lap. Margin Penjualan Produk", "rptmarginpenjualanproduk", "admin/rpt/rptmarginpenjualanproduk", "ion-filing", 800,600,false]
    #["Lap. Arus Kas", "rptaruskas", "admin/rpt/rptaruskas", "ion-filing", 800,600,false]
["Utilitas", "utl", "", "ion-ios-cog"] 
    ["Posting Akhir Hari", "utlpostingakhirhari", "admin/utl/utlpostingakhirhari", "ion-filing", 600,150]
    #["Posting HPP", "utlpostinghpp", "admin/utl/utlpostinghpp", "ion-filing", 900,700]
    ["Posting Akhir Bulan", "utlpostingakhirbln", "admin/utl/utlpostingakhirbln", "ion-filing", 600,600]
    ["Posting Akhir Tahun", "utlpostingakhirthn", "admin/utl/utlpostingakhirthn", "ion-filing", 600,600]
    ["Konversi", "utlkonversi", "admin/utl/utlkonversi", "ion-filing", 600,600]
    ["Backup Database", "utlbackupdb", "admin/utl/utlbackupdb", "",600,70]
["Konfigurasi", "cfg", "", "ion-ios-cog"] 
    ["Config", "config", "admin/config/config", "" ,900, 550, false]
    ["Username", "username", "admin/config/username", "" ,400, 450, false]
	["Username Level", "username_lv", "admin/config/username_lv", "" ,400, 550, false]
