<?php defined('BASEPATH') OR exit('No direct script access allowed') ; ?>
#Nama, Obj, Lokasi, Icon, Lebar, Tinggi, title, resize, modal, frame, help, bodyclass, headerclass
#["Dashboard Center", "d", "admin/dash/d", "ion-ios-speedometer", 0, 0, false]
["Master", "mst", "", "ion-ios-briefcase"]
  ["Rekening", "mstrekening", "admin/mst/mstrekening", "" ,800, 500, false]
  ["Tarif", "msttarif", "admin/mst/msttarif", "" ,800, 500, false]
  #["Golongan Aktiva", "mstgolakt", "admin/mst/mstgolakt", "" ,800, 500, false]
  #["Kelompok Aktiva", "mstkelakt", "admin/mst/mstkelakt", "" ,800, 500, false]
  #["Master Aktiva", "mstakt", "admin/mst/mstakt", "" ,800, 500, false]
  #["Penutupan Aktiva", "msttutupakt", "admin/mst/msttutupakt", "" ,800, 500, false]
["Transaksi", "tr", "", "ion-ios-briefcase"]
  ["Pendaftaran Pelanggan", "mstpelanggan", "admin/mst/mstpelanggan", "ion-filing", 1000, 600, false] 
  ["Kasir", "trkasir", "admin/mst/trkasir", "ion-cash",800, 700] 
  ["Kas Masuk dan Keluar", "trkas", "admin/mst/trkas", "ion-cash", 600, 250]
  ["Jurnal Umum", "trjurnal", "admin/mst/trjurnal", "ion-cash", 850, 600]
["Laporan", "rpt", "", "ion-ios-paper"] 
  ["Kunjungan Pelanggan", "rptkunjungan", "admin/mst/rptkunjungan", "ion-filing", 1000,600]
  ["Absensi Member", "rptabsensi", "admin/mst/rptabsensi", "ion-filing", 1050,600] 
  ["Rekap Jadwal Bayar", "trjadwalbayar", "admin/mst/trjadwalbayar", "ion-filing", 1000,600]
  ["Pembayaran per member", "rptbayar", "admin/mst/rptbayar", "ion-filing", 600,550]
  ["Jadwal Bayar per member", "rptjdwlpel", "admin/mst/rptjdwlpel", "ion-filing", 800,550]
  ["Kas Masuk dan Keluar", "rptkas", "admin/mst/rptkas", "ion-filing", 900,600]
  ["Buku Besar", "rptbukubesar", "admin/mst/rptbukubesar", "ion-filing", 900,600]
  ["Jurnal", "rptjurnal", "admin/mst/rptjurnal", "ion-filing", 800,600] 
  ["Neraca", "rptneraca", "admin/mst/rptneraca", "ion-filing", 800,700]
  ["Laba Rugi", "rptlr", "admin/mst/rptlr", "ion-filing", 800,700]
["Konfigurasi", "cfg", "", "ion-ios-cog"]
  ["Setting Hari Libur", "configlibur", "admin/mst/configlibur", "" ,1100, 620]
  ["Username", "username", "admin/config/username", "" ,400, 450, false]
  ["Username Level", "username_lv", "admin/config/username_lv", "" ,400, 550, false]
