<?php defined('BASEPATH') OR exit('No direct script access allowed') ; ?>
#Nama, Obj, Lokasi, Icon, Lebar, Tinggi, title, resize, modal, frame, help, bodyclass, headerclass
["Dashboard Center", "d", "admin/dash/d", "ion-ios-speedometer", 0, 0, false]
["Customer", "mstcustomer", "admin/mst/mstcustomer", "ion-filing", 1100, 700, false]
["Pendaftaran Anggota", "daftaranggota", "admin/mst/daftaranggota", "ion-filing", 1100, 700, false] 
["Master Data", "mst", "", "ion-ios-briefcase"] 
  ["Kantor", "mstkantor", "admin/mst/mstkantor", "" ,900, 600, false]
  ["Agama", "mstagama", "admin/mst/mstagama", "" ,700, 500, false]
  ["Dati 2", "mstdati2", "admin/mst/mstdati2", "" ,800, 500, false]
  ["Rekening", "mstrekening", "admin/mst/mstrekening", "" ,800, 500, false]
["Master Tabungan", "msttab", "", "ion-ios-briefcase"]  
  ["Golongan Tabungan", "tabungangolongan", "admin/mst/tabungangolongan", "ion-filing", 1000, 600, false] 
  ["Kode Transaksi", "tabungankodetransaksi", "admin/mst/tabungankodetransaksi", "ion-filing", 700, 500, false] 
  ["Perubahan Suku Bunga", "tabunganperubahanrate", "admin/mst/tabunganperubahanrate", "ion-filing", 800, 500, false]
["Transaksi Tabungan", "trtabungan", "", "ion-ios-briefcase"] 
  ["Pembukaan Rekening Tabungan", "trtabunganpembukaan", "admin/tr/trtabunganpembukaan", "ion-filing", 1000, 600, false]    
  ["Transaksi", "trxtabungan_transaksi", "admin/tr/tabungan_transaksi", "ion-cash",800, 700]  
["Laporan Tabungan", "rpttabungan", "", "ion-ios-paper"] 
  ["Pembukaan Rekening", "rptkunjungan", "admin/mst/rptkunjungan", "ion-filing", 1000,600]
  ["Mutasi Harian", "rptabsensi", "admin/mst/rptabsensi", "ion-filing", 1050,600] 
  ["Buku Tabungan", "trjadwalbayar", "admin/mst/trjadwalbayar", "ion-filing", 1000,600]
  ["Saldo Tabungan", "rptbayar", "admin/mst/rptbayar", "ion-filing", 600,550]
["Konfigurasi", "cfg", "", "ion-ios-cog"]
  ["Setting Hari Libur", "configlibur", "admin/mst/configlibur", "" ,1100, 620]
  ["Username", "username", "admin/config/username", "" ,700, 450, false]
  ["Username Level", "username_lv", "admin/config/username_lv", "" ,550, 550, false]