<?php defined('BASEPATH') OR exit('No direct script access allowed') ; ?>
#Nama, Obj, Lokasi, Icon, Lebar, Tinggi, title, resize, modal, frame, help, bodyclass, headerclass
["Dashboard Center", "d", "admin/dash/d", "ion-ios-speedometer", 0, 0, false]
["Customer", "mstcustomer", "admin/mst/mstcustomer", "ion-filing", 1100, 700, false]
["Pendaftaran Anggota", "daftaranggota", "admin/mst/daftaranggota", "ion-filing", 1200, 700, false] 
["Master Data", "mst", "", "ion-ios-briefcase"] 
  ["Kantor", "mstkantor", "admin/mst/mstkantor", "" ,900, 600, false]
  ["Agama", "mstagama", "admin/mst/mstagama", "" ,700, 500, false]
  ["Dati 2", "mstdati2", "admin/mst/mstdati2", "" ,800, 500, false]
  ["Rekening", "mstrekening", "admin/mst/mstrekening", "" ,800, 500, false]
["Master Tabungan", "msttab", "", "ion-ios-briefcase"]  
  ["Golongan Tabungan", "tabungangolongan", "admin/mst/tabungangolongan", "ion-filing", 1000, 600, false] 
  ["Kode Transaksi", "tabungankodetransaksi", "admin/mst/tabungankodetransaksi", "ion-filing", 700, 500, false] 
  ["Perubahan Suku Bunga", "tabunganperubahanrate", "admin/mst/tabunganperubahanrate", "ion-filing", 800, 500, false]
["Master Kredit", "mstkre", "", "ion-ios-briefcase"]
  ["Golongan Kredit", "mstkreditgolongan", "admin/mst/mstkreditgolongan", "ion-filing", 1000, 600, false]
["Transaksi Tabungan", "trtabungan", "", "ion-ios-briefcase"] 
  ["Pembukaan Rekening Tabungan", "trtabunganpembukaan", "admin/tr/trtabunganpembukaan", "ion-filing", 1000, 600, false]    
  ["Transaksi", "trtabungantransaksi", "admin/tr/trtabungantransaksi", "ion-cash",800, 700,false]   
["Transaksi Kredit", "trkre", "", "ion-ios-briefcase"]
  ["Realisasi Kredit", "trkreditrealisasi", "admin/tr/trkreditrealisasi", "ion-filing", 1000, 600, false] 
  ["Pencairan Kredit", "trkreditpencairan", "admin/tr/trkreditpencairan", "ion-filing", 1000, 600, false] 
  ["Transaksi Angsuran", "trangsuran", "admin/tr/trangsuran", "ion-cash",800, 700] 
["Laporan Tabungan", "rpttabungan", "", "ion-ios-paper"] 
  ["Laporan Pembukaan Rekening", "rpttabunganpembukaan", "admin/rpt/rpttabunganpembukaan", "ion-filing", 1000,600]
  ["Laporan Mutasi Harian", "rpttabunganmutasi", "admin/rpt/rpttabunganmutasi", "ion-filing", 1050,600] 
  ["Laporan Buku Tabungan", "rpttabunganbuku", "admin/rpt/rpttabunganbuku", "ion-filing", 1000,600,false]
  ["Laporan Saldo Tabungan", "rpttabungansaldo", "admin/rpt/rpttabungansaldo", "ion-filing", 1100,600,false]
["Laporan Kredit", "rptkre", "", "ion-ios-paper"]   
  ["Laporan Realisasi Kredit", "rptkreditrealisasi", "admin/rpt/rptkreditrealisasi", "ion-filing", 1000,600]
  ["Laporan Agunan", "rptkreditagunan", "admin/rpt/rptkreditagunan", "ion-filing", 1000,600] 
  ["Laporan Mutasi Harian", "rptkreditmutasi", "admin/rpt/rptkreditmutasi", "ion-filing", 1000,600]
  ["Laporan Kartu Angsuran", "rptkreditkartu", "admin/rpt/rptkreditkartu", "ion-filing", 1000,600]
  ["Laporan Baki Debet", "rptkreditbakidebet", "admin/rpt/rptkreditbakidebet", "ion-filing", 1000,600] 
["Konfigurasi", "cfg", "", "ion-ios-cog"]
  ["Setting Hari Libur", "configlibur", "admin/mst/configlibur", "" ,1100, 620]
  ["Username", "username", "admin/config/username", "" ,700, 450, false]
  ["Username Level", "username_lv", "admin/config/username_lv", "" ,550, 550, false]