<?php defined('BASEPATH') OR exit('No direct script access allowed') ; ?>
#Nama, Obj, Lokasi, Icon, Lebar, Tinggi, title, resize, modal, frame, help, bodyclass, headerclass
["Dashboard Center", "d", "admin/dash/d", "ion-ios-speedometer", 0, 0, false]
["Customer", "mstcustomer", "admin/mst/customer", "ion-filing", 1000, 600, false]
["Pendaftaran Anggota", "daftaranggota", "admin/mst/daftaranggota", "ion-filing", 1000, 600, false] 
["Master Data", "mst", "", "ion-ios-briefcase"] 
  ["Agama", "mstagama", "admin/mst/mstagama", "" ,800, 500, false]
  ["Dati 2", "mstdati2", "admin/mst/mstdati2", "" ,800, 500, false]
  ["Rekening", "mstrekening", "admin/mst/mstrekening", "" ,800, 500, false]
["Master Tabungan", "msttab", "", "ion-ios-briefcase"]  
  ["Golongan Tabungan", "tabungangolongan", "admin/mst/tabungangolongan", "ion-filing", 1000, 600, false] 
  ["Kode Transaksi", "tabungankodetransaksi", "admin/mst/tabungankodetransaksi", "ion-filing", 1000, 600, false] 
  ["Perubahan Suku Bunga", "tabunganperubahanrate", "admin/mst/tabunganperubahanrate", "ion-filing", 1000, 600, false]
["Master Deposito", "mstdep", "", "ion-ios-briefcase"]
  ["Golongan Deposito", "mstgoldeposito", "admin/mst/deposito_golongan", "ion-filing", 1000, 600, false] 
  ["Kode Transaksi", "mstkodetrxdeposito", "admin/mst/deposito_kodetransaksi", "ion-filing", 1000, 600, false] 
  ["Perubahan Suku Bunga", "mstubahratedeposito", "admin/mst/deposito_perubahanrate", "ion-filing", 1000, 600, false]
["Master Kredit", "mstkre", "", "ion-ios-briefcase"]
  ["Golongan Kredit", "mstgolkredit", "admin/mst/kredit_golongan", "ion-filing", 1000, 600, false] 
  ["Kode Transaksi", "mstkodetrxkredit", "admin/mst/kredit_kodetransaksi", "ion-filing", 1000, 600, false] 
  ["Perubahan Suku Bunga", "mstubahratekredit", "admin/mst/kredit_perubahanrate", "ion-filing", 1000, 600, false]
["Transaksi Tabungan", "trtabungan", "", "ion-ios-briefcase"]
  ["Pembukaan Rekening Tabungan", "trxtabungan_pembukaan", "admin/tr/tabungan_pembukaan", "ion-filing", 1000, 600, false] 
  ["Transaksi", "trxtabungan_transaksi", "admin/tr/tabungan_transaksi", "ion-cash",800, 700] 
["Transaksi Deposito", "trdeposito", "", "ion-ios-briefcase"] 
  ["Pembukaan Rekening Deposito", "trxdeposito_pembukaan", "admin/tr/deposito_pembukaan", "ion-filing", 1000, 600, false] 
  ["Transaksi", "trxdeposito_transaksi", "admin/tr/deposito_transaksi", "ion-cash",800, 700] 
["Transaksi Kredit", "trkredit", "", "ion-ios-briefcase"]
  ["Realisasi Kredit", "trtrealisasikredit", "admin/tr/kredit_realisasi", "ion-filing", 1000, 600, false] 
  ["Pencairan Kredit", "trpencairankredit", "admin/tr/kredit_pencairan", "ion-filing", 1000, 600, false] 
  ["Transaksi", "trkasir", "admin/tr/kredit_transaksi", "ion-cash",800, 700] 
["Transaksi Akuntansi", "trakuntansi", "", "ion-ios-briefcase"]
  ["Kas Masuk dan Keluar", "trakuntansikas", "admin/tr/trakuntansi_kas", "ion-cash", 600, 250]
  ["Kas Opname", "trakuntansikasopname", "admin/tr/trakuntansi_kasopname", "ion-cash", 600, 250]
  ["Pemindahbukuan", "trpemindahbukuan", "admin/tr/trakuntansi_pemindahbukuan", "ion-cash", 850, 600]
["Aktiva", "aktiva", "", "ion-ios-briefcase"]
  ["Golongan Aktiva", "mstgolakt", "admin/mst/mstgolakt", "" ,800, 500, false]
  ["Kelompok Aktiva", "mstkelakt", "admin/mst/mstkelakt", "" ,800, 500, false]
  ["Master Aktiva", "mstakt", "admin/mst/mstakt", "" ,800, 500, false]
  ["Penutupan Aktiva", "msttutupakt", "admin/mst/msttutupakt", "" ,800, 500, false]
["Laporan", "rpt", "", "ion-ios-paper"] 
  ["Kunjungan Pelanggan", "rptkunjungan", "admin/mst/rptkunjungan", "ion-filing", 1000,600]
  ["Absensi Member", "rptabsensi", "admin/mst/rptabsensi", "ion-filing", 1050,600] 
  ["Rekap Jadwal Bayar", "trjadwalbayar", "admin/mst/trjadwalbayar", "ion-filing", 1000,600]
  ["Pembayaran per member", "rptbayar", "admin/mst/rptbayar", "ion-filing", 600,550]
  ["Jadwal Bayar per member", "rptjdwlpel", "admin/mst/rptjdwlpel", "ion-filing", 800,550]
  ["Kas Masuk dan Keluar", "rptkas", "admin/mst/rptkas", "ion-filing", 900,600]
  ["Buku Besar", "rptbukubesar", "admin/mst/rptbukubesar", "ion-filing", 900,600]
  ["Jurnal", "rptjurnal", "admin/mst/rptjurnal", "ion-filing", 800,600] 
  ["Neraca", "rptneraca", "admin/mst/rptneraca", "ion-filing", 800,700]
  ["Laba Rugi", "rptlr", "admin/mst/rptlr", "ion-filing", 800,700]
["Konfigurasi", "cfg", "", "ion-ios-cog"]
  ["Setting Hari Libur", "configlibur", "admin/mst/configlibur", "" ,1100, 620]
  ["Username", "username", "admin/config/username", "" ,400, 450, false]
  ["Username Level", "username_lv", "admin/config/username_lv", "" ,400, 550, false]